export default {
  API_BASE_URL: process.env.REACT_APP_API_BASE_URL,
  API_AUTH_URL: process.env.REACT_APP_API_AUTH_URL,
  POOSUU_PUBLIC_API_KEY: process.env.REACT_APP_POOSUU_PUBLIC_API_KEY,
  POOSUU_ADMIN_DATA: "POOSUU_ADMIN_DATA",
  POOSUU_ADMIN_ACCESS_TOKEN: "POOSUU_ADMIN_ACCESS_TOKEN",
  // API_BASE_URL: "http://127.0.0.1:5000/v1",
};
